name: Publish Modules

on:
  push:
    tags:
      - "v*"

jobs:

  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Tag
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

  
  tag-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Extract Tag
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: tag api
        run: |
          git tag api/${{ steps.extract_tag.outputs.tag }}

      - name: tag common
        run: |
          git tag common/${{ steps.extract_tag.outputs.tag }}

      - name: tag k8sutils
        run: |
          git tag k8sutils/${{ steps.extract_tag.outputs.tag }}

      - name: tag procdiscovery
        run: |
          git tag procdiscovery/${{ steps.extract_tag.outputs.tag }}

      - name: tag odiglet
        run: |
          git tag odiglet/${{ steps.extract_tag.outputs.tag }}

      - name: Push Module Tags
        run: |
          git push origin --tags

  publish-docker-images:
    strategy:
      matrix:
        include:
          - service: autoscaler
            runner: ubuntu-latest
          - service: scheduler
            runner: ubuntu-latest
          - service: instrumentor
            runner: ubuntu-latest
          - service: collector
            runner: large-runner
          - service: odiglet
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Tag
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image for ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: joeylee1997/odigos-${{ matrix.service }}:${{ steps.extract_tag.outputs.tag }}
          build-args: SERVICE_NAME=${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          file: >-
            ${{
              (matrix.service == 'odiglet' && 'odiglet/Dockerfile') ||
              (matrix.service == 'collector' && 'collector/Dockerfile') ||
              'Dockerfile'
            }}
          context: >-
            ${{
              (matrix.service == 'collector' && 'collector') ||
              '.'
            }}

     